# Generated by Django 2.2.16 on 2022-06-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientrecipeamount',
            unique_together=set(),
        ),
    ]
